name: Sync FreeNodes

on:
schedule:
- cron: '*/30 * * * *'   # 每30分钟运行一次
workflow_dispatch:

jobs:
sync:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Sync upstream
    uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
    with:
      upstream_sync_repo: shuaidaoya/FreeNodes
      upstream_sync_branch: main
      target_sync_branch: main
      target_repo_token: ${{ secrets.GITHUB_TOKEN }}
